# Generated by Django 3.0.6 on 2020-06-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerClass', models.CharField(blank=True, max_length=10000, null=True)),
                ('No_siblings', models.CharField(blank=True, max_length=10000, null=True)),
                ('No_children', models.CharField(blank=True, max_length=10000, null=True)),
                ('female', models.CharField(blank=True, max_length=10000, null=True)),
                ('male', models.CharField(blank=True, max_length=10000, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
